-- ============================================
-- Migration: Make prescription images private (PHI protection) — PU-2
-- Date: 2026-06-11
-- Purpose:
--   Prescription images are Protected Health Information. The original
--   `prescriptions_public_read` policy (20260517) made every object in the
--   'prescriptions' bucket world-readable to anyone with the URL. This migration
--   makes the bucket private and restricts SELECT to:
--     (a) the uploading customer (storage object owner), and
--     (b) the PHARMACY assigned to the order that references the object.
--   Images are served to the pharmacy via short-lived signed URLs generated by
--   the client (createSignedUrl), which only succeed when these RLS SELECT
--   policies grant access.
--
--   Upload/update policies for the owner are preserved. No other bucket affected.
-- ============================================

-- 1. Make the bucket private (signed URLs only).
UPDATE storage.buckets
SET public = false
WHERE id = 'prescriptions';

-- 1a. Ensure the column the pharmacy-read policy depends on exists.
--     (Idempotent: matches 20260509; guards instances where that migration was not applied.)
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS prescription_url TEXT;

-- 2. Remove the world-readable policy.
DROP POLICY IF EXISTS prescriptions_public_read ON storage.objects;

-- 3. Owner (uploading customer) can read their own prescription objects.
DROP POLICY IF EXISTS prescriptions_owner_read ON storage.objects;
CREATE POLICY prescriptions_owner_read
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'prescriptions'
    AND owner = auth.uid()
);

-- 4. The PHARMACY assigned to an order may read the prescription referenced by that order.
--    Object file names are flat (e.g. "<customerId>_<ts>_<uuid>.<ext>") and the order's
--    prescription_url ends with that file name, so we match on the object name suffix.
DROP POLICY IF EXISTS prescriptions_pharmacy_read ON storage.objects;
CREATE POLICY prescriptions_pharmacy_read
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'prescriptions'
    AND EXISTS (
        SELECT 1
        FROM public.orders o
        JOIN public.profiles p ON p.pharmacy_id = o.pharmacy_id
        WHERE p.id = auth.uid()
          AND p.account_type = 'PHARMACY'
          AND p.is_active = true
          AND o.order_type = 'CUSTOMER_PHARMACY'
          AND o.prescription_url IS NOT NULL
          AND o.prescription_url LIKE '%' || storage.objects.name
    )
);
